### ISSUE TITLE
ContainerSSH does not work with Jetbrain remote development

### ISSUE THREAD

**Issue by hongkunyoo** [ContainerSSH/ContainerSSH#536]
## Please describe what you need help with:

I want to use [Jetbrain remote development](https://www.jetbrains.com/help/idea/2022.2/remote-development-starting-page.html) with ContainerSSH but failed.

I've checked that the plain ssh and sftp works on my ContainerSSH.
However whenever I connect with Jetbrain remote development using SSH connection, it gets timeout and fail.

I've looked at this issue(https://github.com/ContainerSSH/ContainerSSH/issues/485), but it seems different issue.(I'm not 100% sure though)
I'm currently using following version:
- ContainerSSH: [7543c89](https://github.com/ContainerSSH/ContainerSSH/commit/7543c897ac54dcf544175f1b88f88c94886e113d)

<details>
 <summary>Jetbrain remote development logs</summary>

```java
2022-10-31 23:23:25,680 [42423827]   INFO - #c.j.g.s.d.DeployErrorProcessor - Worker binary deploy failed with deploy exception
com.jetbrains.gateway.ssh.deploy.DeployException: Worker binary deploy failed: check command log for details: Timeout expired
	at com.jetbrains.gateway.ssh.GoWorkerDeployer.deploy$intellij_gateway_core(GoWorkerDeployer.kt:219)
	at com.jetbrains.gateway.ssh.GoWorkerDeployer$deploy$1.invokeSuspend(GoWorkerDeployer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.ssh.SshException: Timeout expired
	at com.intellij.ssh.impl.sshj.SshjSshConnection.openChannel(SshjSshConnection.kt:55)
	at com.intellij.ssh.impl.SshConnection$openChannel$1.invoke(SshConnection.kt:67)
	at com.intellij.ssh.impl.SshConnection$openChannel$1.invoke(SshConnection.kt:27)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall(ssh.kt:386)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall$default(ssh.kt:369)
	at com.intellij.ssh.impl.SshConnection.openChannel(SshConnection.kt:56)
	at com.intellij.ssh.SshConnectionService.exec(SshConnectionService.kt:215)
	at com.intellij.ssh.ExecBuilder.execute(ssh.kt:213)
	at com.intellij.ssh.ExecBuilder.execute$default(ssh.kt:207)
	at com.jetbrains.gateway.ssh.deploy.impl.SshCommandExecutor$executeCommand$process$1.invoke(SshCommandExecutor.kt:53)
	at com.jetbrains.gateway.ssh.deploy.impl.SshCommandExecutor$executeCommand$process$1.invoke(SshCommandExecutor.kt:27)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: net.schmizz.sshj.connection.ConnectionException: Timeout expired
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:105)
	at net.schmizz.sshj.connection.channel.direct.SessionChannel.exec(SessionChannel.java:102)
	at com.intellij.ssh.impl.sshj.SshjSshConnection.execChannel(SshjSshConnection.kt:83)
	at com.intellij.ssh.SshConnectionService$exec$1.invoke(SshConnectionService.kt:217)
	at com.intellij.ssh.SshConnectionService$exec$1.invoke(SshConnectionService.kt:35)
	at com.intellij.ssh.impl.sshj.SshjSshConnection.openChannel(SshjSshConnection.kt:49)
	... 19 more
Caused by: java.util.concurrent.TimeoutException: Timeout expired
	... 26 more
2022-10-31 23:23:25,683 [42423830]   INFO - #c.j.g.s.d.LoggingHostCommandExecutorWrapper - $CONTAINERSSH_HOST :: uname -sm :: exit code: 0 :: stdout: Linux x86_64 :: stderr: 
2022-10-31 23:23:25,683 [42423830]   INFO - #c.j.g.s.d.LoggingHostCommandExecutorWrapper - $CONTAINERSSH_HOST :: uname -sm :: exit code: 0 :: stdout: Linux x86_64 :: stderr: 
2022-10-31 23:23:25,683 [42423830]   INFO - #c.j.g.s.d.LoggingHostCommandExecutorWrapper - $CONTAINERSSH_HOST :: echo $HOME :: exit code: 0 :: stdout: /home/jovyan :: stderr: 
```
</details>

Could you take a look on this?
Thanks for the awesome work!

**Comment by tsipinakis** [comment]
Version 0.5 has been released which supports port forwarding and thus remote development. Closing this as solved. Please report any issues you find with it.
